# Default Configuration for ResNet50 t-SNE Visualization

# Model configuration
model:
  architecture: resnet50
  num_classes: 10
  pretrained: false
  pretrained_path: ./models/resNet50.pth
  extract_layer: avgpool  # Options: layer1, layer2, layer3, layer4, avgpool

# Data configuration
data:
  dataset: cifar10
  data_root: ./data
  batch_size: 128
  num_workers: 4
  shuffle: true
  pin_memory: true
  split: val  # Options: train, val, test

# Data augmentation
augmentation:
  train:
    random_crop: true
    random_flip: true
    color_jitter: false
    rotation: false
  val:
    resize: 256
    center_crop: 224

# Normalization (ImageNet statistics)
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# t-SNE configuration
tsne:
  n_components: 2
  perplexity: 30
  n_iter: 1000
  learning_rate: 200.0
  random_state: 42
  metric: euclidean
  init: random
  verbose: 1

# Visualization configuration
visualization:
  figsize: [20, 20]
  dpi: 300
  point_size: 20
  font_size: 20
  colormap: jet
  save_format: jpg
  show_plot: true
  remove_axes: true
  remove_borders: true

# System configuration
system:
  device: cuda  # Options: cuda, cpu, auto
  seed: 42
  deterministic: true

# Output configuration
output:
  save_features: true
  features_path: ./results/features.npz
  visualization_path: ./results/tsne_visualization.jpg
  class_indices_path: ./results/class_indices.json

# Logging configuration
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: ./logs/feature_extraction.log